project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1.qmd
          - text: Hands-on Exercise 2
            href: Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2.qmd 
          - text: Hands-on Exercise 3
            href: Hands-on_Ex/Hands-on_Ex3/Hands-on_Ex3.qmd
          - text: Hands-on Exercise 4
            href: Hands-on_Ex/Hands-on_Ex4/Hands-on_Ex4.qmd
          - text: Hands-on Exercise 5
            href: Hands-on_Ex/Hands-on_Ex5/Hands-on_Ex5.qmd
            
      - text: In-Class Exercises
        menu: 
          - text: In-Class Exercise 1
            href: In-Class_Ex/In-class_Ex1/In-class_Ex1.qmd
          - text: In-Class Exercise 2
            href: In-Class_Ex/In-class_Ex2/In-class_Ex2.qmd
          - text: In-Class Exercise 3
            href: In-Class_Ex/In-class_Ex3/In-class_Ex3.qmd
          - text: In-Class Exercise 4
            href: In-Class_Ex/In-class_Ex4/In-class_Ex4.qmd
          - text: In-Class Exercise 5
            href: In-Class_Ex/In-class_Ex5/In-class_Ex5.qmd
            
            
      - text: Take-Home Exercises
        menu: 
          - text: Take-Home Exercise 1
            href: Take-Home_Ex/Take-Home_Ex1/Take-Home_Ex1.qmd
          - text: Take-Home Exercise 2
            href: Take-Home_Ex/Take-Home_Ex2/Take-Home_Ex2.qmd
          - text: Take-Home Exercise 3
            href: Take-Home_Ex/Take-Home_Ex3/Take-Home_Ex3.qmd
       
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

